Controllers films users
Dmitrii-Petrov/java-filmorate pull request #3
Opened 2023-04-03 23:12 UTC by Dmitrii-Petrov

2023-04-04 04:02 UTC, db-exp requested changes

2023-04-04 04:02 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/servise/ValidateService.java
> +    public void validateFilm(Film film) {
для удобства можно сделать кастомную аннотацию https://blog.clairvoyantsoft.com/spring-boot-creating-a-custom-annotation-for-validation-edafbf9a97a4

2023-04-04 04:02 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/servise/ValidateService.java
> +            throw new RuntimeException("кино еще не изобрели");
лучше кидать кастомную ошибку ValidationException

2023-04-04 04:02 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    String name;
можно максимальный размер задать

2023-04-04 04:02 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +            throw new RuntimeException("фильм не существует");
тут тоже можно и лучше сразу делать NotFoundException

2023-04-04 21:15 UTC, Dmitrii-Petrov commented on src/main/java/ru/yandex/practicum/filmorate/servise/ValidateService.java
> +            throw new RuntimeException("кино еще не изобрели");
done

2023-04-04 21:16 UTC, Dmitrii-Petrov commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +            throw new RuntimeException("фильм не существует");
поменял на NoSuchElementException

2023-04-04 21:21 UTC, Dmitrii-Petrov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    String name;
done

2023-04-05 04:01 UTC, db-exp approved these changes

2023-04-05 06:20 UTC, merged